language: node_js
services: mongodb
node_js:
- '0.10'
install:
  - npm install
script:
  - npm test
env:
  global:
    - LOCAL_CONNECT_URL="NP"
    - LOCAL_ANYFETCH_ID="CLUESTR-ID"
    - LOCAL_ANYFETCH_SECRET="CLUESTR-SECRET"
