language: node_js
services:
  - mongodb
  - redis-server
node_js:
- '0.10'
install:
  - npm install
script:
  - npm test
env:
  global:
    - PROVIDER_URL="http://localhost:8000"
    - ANYFETCH_API_ID="none"
    - ANYFETCH_API_SECRET="none"
